# Database Connection (Postgres.app uses your Mac username and NO password)
spring.datasource.url=jdbc:postgresql://localhost:5432/calculator_db
spring.datasource.username=nokhinchau
spring.datasource.password=

# Tell Spring Boot to automatically create your database tables based on your Java code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true